language: cpp

dist: xenial

matrix:
  include:
    - env:
        - LLVM_VERSION=6.0
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
            - ubuntu-toolchain-r-test
          packages:
            # From sources above
            - llvm-6.0-dev
            - clang-6.0
    - env:
        - LLVM_VERSION=7
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
          packages:
            # From sources above
            - llvm-7-dev
            - clang-7
    - env:
        - LLVM_VERSION=8
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
            # From sources above
            - llvm-8-dev
            - clang-8

before_install:
  - export LLVM_CONFIG="llvm-config-${LLVM_VERSION}"

script:
  - mkdir build
  - cd build
  - cmake .. -DLLVM_CONFIG=$LLVM_CONFIG
  - make -j4
