language: cpp

dist: xenial

cache:
  apt: true

matrix:
  include:
    - env:
        - LLVM_VERSION=6.0
        # llvm passes -Werror=date-time which is only supported in gcc-4.9+
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
            - ubuntu-toolchain-r-test
          packages:
            - libedit-dev
            # LLVM-6 needs libstdc++4.9
            - g++-4.9
            # From sources above
            - llvm-6.0-dev
            - clang-6.0
    - env:
        - LLVM_VERSION=7
        # llvm passes -Werror=date-time which is only supported in gcc-4.9+
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
          packages:
            - libedit-dev
            # LLVM-7 needs libstdc++4.9
            - g++-4.9
            # From sources above
            - llvm-7-dev
            - clang-7
    - env:
        - LLVM_VERSION=8
        # llvm passes -Werror=date-time which is only supported in gcc-4.9+
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
            - libedit-dev
            - g++-4.9
            # From sources above
            - llvm-8-dev
            - clang-8

before_install:
    - eval "${MATRIX_EVAL}"
    - export LLVM_CONFIG="llvm-config-${LLVM_VERSION}"

script:
   - mkdir build
   - cd build
   - cmake .. -DLLVM_CONFIG=$LLVM_CONFIG -DCMAKE_FIND_DEBUG_MODE=ON
   - make -j4
