name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm: ["6.0", "7", "8"]
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: Install dependencies
      env:
        LLVM_VERSION: ${{ matrix.llvm }}
      run: sudo apt-get install libgraphviz-dev libginac-dev llvm-$LLVM_VERSION-dev
    - name: Configure
      run: |
         mkdir _build
         cd _build
         cmake ..
    - name: Make
      run: |
        cd _build
        make -j4
